MODULE_METHODS = {
    "Airline": ["aircraftType", "airline", "airplane", "airport", "flightNumber", "recordLocator", "seat"],
    "Animal": ["bear", "bird", "cat", "cetacean", "cow", "crocodilia", "dog", "fish", "horse", "insect", "lion", "petName", "rabbit", "rodent", "snake", "type"],
    "Book": ["author", "format", "genre", "publisher", "series", "title"],
    "Color": ["cmyk", "colorByCSSColorSpace", "cssSupportedFunction", "cssSupportedSpace", "hsl", "human", "hwb", "lab", "lch", "rgb", "space"],
    "Commerce": ["department", "isbn", "price", "product", "productAdjective", "productDescription", "productMaterial", "productName", "upc"],
    "Company": ["buzzAdjective", "buzzNoun", "buzzPhrase", "buzzVerb", "catchPhrase", "catchPhraseAdjective", "catchPhraseDescriptor", "catchPhraseNoun", "name"],
    "Database": ["collation", "column", "engine", "mongodbObjectId", "type"],
    "Datatype": ["boolean"],
    "Date": ["anytime", "between", "betweens", "birthdate", "future", "month", "past", "recent", "soon", "timeZone", "weekday"],
    "Finance": ["accountName", "accountNumber", "amount", "bic", "bitcoinAddress", "creditCardCVV", "creditCardIssuer", "creditCardNumber", "currency", "currencyCode", "currencyName", "currencyNumericCode", "currencySymbol", "ethereumAddress", "iban", "litecoinAddress", "pin", "routingNumber", "transactionDescription", "transactionType"],
    "Food": ["adjective", "description", "dish", "ethnicCategory", "fruit", "ingredient", "meat", "spice", "vegetable"],
    "Git": ["branch", "commitDate", "commitEntry", "commitMessage", "commitSha"],
    "Hacker": ["abbreviation", "adjective", "ingverb", "noun", "phrase", "verb"],
    "Image": ["avatar", "avatarGitHub", "dataUri", "personPortrait", "url", "urlLoremFlickr", "urlPicsumPhotos"],
    "Internet": ["displayName", "domainName", "domainSuffix", "domainWord", "email", "emoji", "exampleEmail", "httpMethod", "httpStatusCode", "ip", "ipv4", "ipv6", "jwt", "jwtAlgorithm", "mac", "password", "port", "protocol", "url", "userAgent", "username"],
    "Location": ["buildingNumber", "cardinalDirection", "city", "continent", "country", "countryCode", "county", "direction", "language", "latitude", "longitude", "nearbyGPSCoordinate", "ordinalDirection", "postalAddress", "secondaryAddress", "state", "street", "streetAddress", "timeZone", "zipCode"],
    "Lorem": ["lines", "paragraph", "paragraphs", "sentence", "sentences", "slug", "text", "word", "words"],
    "Music": ["album", "artist", "genre", "songName"],
    "Number": ["bigInt", "binary", "float", "hex", "int", "octal", "romanNumeral"],
    "Person": ["bio", "firstName", "fullName", "gender", "jobArea", "jobDescriptor", "jobTitle", "jobType", "lastName", "middleName", "prefix", "sex", "sexType", "suffix", "zodiacSign"],
    "Phone": ["imei", "number"],
    "Science": ["chemicalElement", "unit"],
    "String": ["alpha", "alphanumeric", "binary", "fromCharacters", "hexadecimal", "nanoid", "numeric", "octal", "sample", "symbol", "ulid", "uuid"],
    "System": ["commonFileExt", "commonFileName", "commonFileType", "cron", "directoryPath", "fileExt", "fileName", "filePath", "fileType", "mimeType", "networkInterface", "semver"],
    "Vehicle": ["bicycle", "color", "fuel", "manufacturer", "model", "type", "vehicle", "vin", "vrm"],
    "Word": ["adjective", "adverb", "conjunction", "interjection", "noun", "preposition", "sample", "verb", "words"],
}

DEFAULT_ARGS = {
    "color.colorByCSSColorSpace": [{"space": "sRGB", "format": "css"}],
    "date.between": [{"from": "2020-01-01T00:00:00.000Z", "to": "2030-01-01T00:00:00.000Z"}],
    "date.betweens": [{"from": "2020-01-01T00:00:00.000Z", "to": "2030-01-01T00:00:00.000Z", "count": 2}],
    "string.fromCharacters": ["ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"],
}

CATEGORY_EXAMPLES = {
    "Airline": ["narrowbody", "South African Airways", "OSL"],
    "Animal": ["red fox", "tabby", "goldfish"],
    "Book": ["The Silent Patient", "Hardcover", "Mystery"],
    "Color": ["#7f4acb", "rgb(120, 45, 210)", "lavender"],
    "Commerce": ["Electronics", "49.99", "Handcrafted Steel Chair"],
    "Company": ["Acme LLC", "innovative", "streamline"],
    "Database": ["users", "InnoDB", "uuid"],
    "Datatype": ["true", "false", "true"],
    "Date": ["2027-03-14T09:15:30.000Z", "Monday", "America/New_York"],
    "Finance": ["USD", "4532015112830366", "GB29NWBK60161331926819"],
    "Food": ["tangy", "Pad Thai", "basil"],
    "Git": ["main", "fix parser edge case", "a3f4c9b"],
    "Hacker": ["TCP", "neural", "bypass"],
    "Image": ["https://example.com/avatar.png", "data:image/png;base64,...", "https://picsum.photos/640/480"],
    "Internet": ["jane.doe@example.com", "https://example.com", "192.168.0.1"],
    "Location": ["Berlin", "Germany", "90210"],
    "Lorem": ["lorem ipsum", "quick brown fox", "dolor sit amet"],
    "Music": ["Kind of Blue", "Miles Davis", "Jazz"],
    "Number": ["42", "7.5", "1337"],
    "Person": ["James", "Thornton", "James Thornton"],
    "Phone": ["555-123-4567", "+1-202-555-0174", "49-015-399-5832"],
    "Science": ["Hydrogen", "meter", "kelvin"],
    "String": ["abc123", "f47ac10b-58cc-4372-a567-0e02b2c3d479", "01HZXK9P8M6Z7C2R4QY"],
    "System": ["report.pdf", "/usr/local/bin", "application/json"],
    "Vehicle": ["Toyota", "Model S", "1HGCM82633A004352"],
    "Word": ["brisk", "carefully", "river"],
}

METHOD_EXAMPLES = {
    "abbreviation": ["TCP", "HTTP", "AI"],
    "accountName": ["Personal Loan Account", "Auto Loan Account", "Savings Account"],
    "accountNumber": ["92842238", "10293847", "67584930"],
    "adjective": ["sleek", "tasty", "practical"],
    "adverb": ["quickly", "carefully", "boldly"],
    "aircraftType": ["narrowbody", "widebody", "regional"],
    "airline": ["South African Airways", "Delta Air Lines", "Lufthansa"],
    "airplane": ["Boeing 747SR", "Airbus A320", "Cessna 172"],
    "airport": ["Oslo Lufthavn", "Heathrow Airport", "Denver International"],
    "album": ["Kind of Blue", "Blue Train", "Rumours"],
    "alpha": ["abc", "QmLp", "xYz"],
    "alphanumeric": ["a1b2c3", "ZX90qa", "m7n8p9"],
    "amount": ["617.49", "84.20", "1200.00"],
    "artist": ["Miles Davis", "Joni Mitchell", "Radiohead"],
    "author": ["Octavia Butler", "Ursula Le Guin", "James Baldwin"],
    "avatar": ["https://avatars.githubusercontent.com/u/12345", "https://example.com/avatar.png", "https://cdn.example.com/user.jpg"],
    "avatarGitHub": ["https://avatars.githubusercontent.com/u/583231", "https://avatars.githubusercontent.com/u/9919", "https://avatars.githubusercontent.com/u/1024"],
    "bear": ["American black bear", "polar bear", "brown bear"],
    "bic": ["DEUTDEFF", "CHASUS33", "BOFAUS3N"],
    "bigInt": ["9007199254740991", "123456789012345", "42"],
    "binary": ["101101", "00011011", "111000"],
    "bird": ["robin", "eagle", "sparrow"],
    "bitcoinAddress": ["1BoatSLRHtKNngkdXEeobR76b53LETtpyT", "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy", "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080"],
    "boolean": ["true", "false", "true"],
    "branch": ["main", "feature/api", "release-2026"],
    "buildingNumber": ["742", "1600", "221B"],
    "buzzAdjective": ["innovative", "scalable", "frictionless"],
    "buzzNoun": ["synergies", "deliverables", "paradigms"],
    "buzzPhrase": ["streamline scalable systems", "enable real-time platforms", "deploy frictionless solutions"],
    "buzzVerb": ["streamline", "architect", "leverage"],
    "cardinalDirection": ["North", "South", "West"],
    "catchPhrase": ["Multi-tiered human-resource flexibility", "User-centric fault-tolerant adapter", "Open-source motivating strategy"],
    "catchPhraseAdjective": ["adaptive", "cross-platform", "virtual"],
    "catchPhraseDescriptor": ["systematic", "holistic", "responsive"],
    "catchPhraseNoun": ["leverage", "framework", "algorithm"],
    "cat": ["Siamese", "Maine Coon", "tabby"],
    "cetacean": ["blue whale", "dolphin", "orca"],
    "chemicalElement": ["Hydrogen", "Oxygen", "Carbon"],
    "city": ["New York", "Berlin", "Tokyo"],
    "cmyk": ["0.1,0.8,0.2,0.0", "0.0,0.3,0.7,0.1", "0.6,0.1,0.0,0.2"],
    "collation": ["utf8_unicode_ci", "utf8mb4_general_ci", "SQL_Latin1_General_CP1_CI_AS"],
    "color": ["blue", "silver", "black"],
    "colorByCSSColorSpace": ["color(srgb 0.4 0.2 0.8)", "color(display-p3 0.9 0.1 0.3)", "color(srgb 0.1 0.8 0.4)"],
    "column": ["id", "created_at", "email"],
    "commitDate": ["2026-03-14T09:15:30.000Z", "2025-11-02T17:44:12.000Z", "2024-06-08T03:21:09.000Z"],
    "commitEntry": ["commit a3f4c9b", "Author: Jane Doe", "fix parser edge case"],
    "commitMessage": ["fix parser edge case", "add settings cache", "update user table"],
    "commitSha": ["a3f4c9b8e2d1", "9b8e7f6a1234", "2cf24dba5fb0"],
    "commonFileExt": ["pdf", "jpg", "txt"],
    "commonFileName": ["invoice.pdf", "profile.jpg", "notes.txt"],
    "commonFileType": ["image", "text", "application"],
    "conjunction": ["and", "but", "or"],
    "continent": ["Europe", "Asia", "North America"],
    "country": ["United States", "Germany", "Japan"],
    "countryCode": ["US", "DE", "JP"],
    "county": ["Orange County", "Cook County", "King County"],
    "cow": ["Holstein", "Angus", "Hereford"],
    "creditCardCVV": ["123", "042", "999"],
    "creditCardIssuer": ["visa", "mastercard", "american_express"],
    "creditCardNumber": ["4532015112830366", "5425233430109903", "371449635398431"],
    "crocodilia": ["alligator", "crocodile", "caiman"],
    "cron": ["*/5 * * * *", "0 9 * * 1", "30 2 1 * *"],
    "currency": ["US Dollar", "Euro", "Japanese Yen"],
    "currencyCode": ["USD", "EUR", "JPY"],
    "currencyName": ["US Dollar", "Euro", "Pound Sterling"],
    "currencyNumericCode": ["840", "978", "392"],
    "currencySymbol": ["$", "€", "¥"],
    "cssSupportedFunction": ["rgb", "hsl", "lab"],
    "cssSupportedSpace": ["sRGB", "display-p3", "rec2020"],
    "dataUri": ["data:image/png;base64,iVBORw0KGgo...", "data:text/plain;base64,SGVsbG8=", "data:image/svg+xml;base64,PHN2Zy..."],
    "department": ["Electronics", "Books", "Garden"],
    "description": ["Tender noodles with spicy sauce", "Crisp pastry with cream", "Smoky grilled vegetables"],
    "directoryPath": ["/usr/local/bin", "/home/user/docs", "/var/log"],
    "direction": ["North", "Southwest", "East"],
    "dish": ["Pad Thai", "Lasagna", "Tacos"],
    "displayName": ["jane_doe", "michael99", "data_wizard"],
    "dog": ["Labrador", "beagle", "poodle"],
    "domainName": ["example.com", "myshop.io", "data.org"],
    "domainSuffix": ["com", "org", "net"],
    "domainWord": ["example", "acme", "cloud"],
    "email": ["jane.doe@example.com", "alex99@test.org", "maria@sample.net"],
    "emoji": ["😀", "🚀", "📦"],
    "engine": ["InnoDB", "MyISAM", "PostgreSQL"],
    "ethereumAddress": ["0x32Be343B94f860124dC4fEe278FDCBD38C102D88", "0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe", "0x8ba1f109551bD432803012645Ac136ddd64DBA72"],
    "ethnicCategory": ["Thai", "Italian", "Mexican"],
    "exampleEmail": ["jane.doe@example.com", "alex.smith@example.org", "user42@example.net"],
    "fileExt": ["pdf", "csv", "png"],
    "fileName": ["report.pdf", "photo.jpg", "data.csv"],
    "filePath": ["/home/user/report.pdf", "/tmp/data.csv", "/var/log/app.log"],
    "fileType": ["image", "text", "application"],
    "fish": ["salmon", "trout", "goldfish"],
    "flightNumber": ["5502", "AA123", "LH400"],
    "float": ["7.5", "42.13", "0.84"],
    "format": ["Hardcover", "Paperback", "Ebook"],
    "fromCharacters": ["A7Q9", "ZX13", "M5NP"],
    "fuel": ["gasoline", "electric", "diesel"],
    "fullName": ["James Thornton", "Maria Chen", "Priya Okafor"],
    "future": ["2028-04-12T10:30:00.000Z", "2027-01-03T14:22:11.000Z", "2029-09-18T08:00:00.000Z"],
    "gender": ["Female", "Male", "Non-binary"],
    "genre": ["Mystery", "Science Fiction", "Biography"],
    "hsl": ["hsl(210, 64%, 52%)", "hsl(12, 88%, 61%)", "hsl(120, 45%, 40%)"],
    "httpMethod": ["GET", "POST", "PATCH"],
    "httpStatusCode": ["200", "404", "500"],
    "human": ["red", "navy blue", "mint green"],
    "hwb": ["hwb(194 0% 0%)", "hwb(120 20% 10%)", "hwb(33 5% 30%)"],
    "hex": ["0x2f", "0xff", "0x1a3b"],
    "hexadecimal": ["0x5f2a", "deadbeef", "a1b2c3"],
    "horse": ["Arabian", "Mustang", "Clydesdale"],
    "iban": ["GB29NWBK60161331926819", "DE89370400440532013000", "FR1420041010050500013M02606"],
    "imei": ["49-015420-323751-8", "35-209900-176148-1", "86-701402-937612-4"],
    "ingredient": ["basil", "ginger", "olive oil"],
    "ingverb": ["backing up", "hacking", "compressing"],
    "insect": ["butterfly", "ant", "dragonfly"],
    "interjection": ["wow", "alas", "hey"],
    "int": ["42", "7", "1337"],
    "ip": ["192.168.0.1", "10.0.0.42", "2001:db8::1"],
    "ipv4": ["192.168.1.1", "10.0.0.42", "172.16.254.1"],
    "ipv6": ["2001:0db8:85a3::8a2e:0370:7334", "fe80::1", "2001:db8::ff00:42:8329"],
    "isbn": ["978-0-306-40615-7", "978-1-56619-909-4", "978-0-13-110362-7"],
    "jobArea": ["Engineering", "Marketing", "Finance"],
    "jobDescriptor": ["Senior", "Lead", "Regional"],
    "jobTitle": ["Senior Data Engineer", "UX Researcher", "Logistics Coordinator"],
    "jobType": ["Administrator", "Designer", "Specialist"],
    "jwt": ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...", "eyJhbGciOiJSUzI1NiJ9...", "eyJ0eXAiOiJKV1QifQ..."],
    "jwtAlgorithm": ["HS256", "RS256", "ES256"],
    "lab": ["lab(54.29% 80.82 69.88)", "lab(70% -20 40)", "lab(35% 10 -30)"],
    "language": ["English", "Spanish", "Japanese"],
    "lastName": ["Thornton", "Nakamura", "Okafor"],
    "latitude": ["40.712776", "-33.868820", "51.507351"],
    "lch": ["lch(52.23% 72.2 56.2)", "lch(80% 40 120)", "lch(45% 30 280)"],
    "lines": ["Dolor sit amet.", "Consectetur adipiscing elit.", "Sed do eiusmod."],
    "lion": ["African lion", "Asiatic lion", "mountain lion"],
    "litecoinAddress": ["LcHKL65Fza8xX2M9JAvZ2H3mGmS9V1RkQy", "Lb6wDP3JfQHkE6cN2aRqM9pXzP7v4yTqX", "M9T1NuD3ZkQ9E5S8fA6jL2hR7pC4bVxY"],
    "longitude": ["-74.005974", "151.209290", "-0.127758"],
    "mac": ["00:1A:2B:3C:4D:5E", "AA:BB:CC:DD:EE:FF", "02:42:AC:11:00:02"],
    "manufacturer": ["Toyota", "Ford", "BMW"],
    "meat": ["chicken", "beef", "pork"],
    "middleName": ["Marie", "Lee", "James"],
    "mimeType": ["application/json", "image/png", "text/html"],
    "model": ["Camry", "F-150", "Model S"],
    "mongodbObjectId": ["507f1f77bcf86cd799439011", "64b7f2a8e13a5d3c9f4a0012", "5f43a1b2c3d4e5f60718293a"],
    "month": ["January", "April", "September"],
    "name": ["Acme LLC", "Globex Corporation", "Initech"],
    "nanoid": ["V1StGXR8_Z5jdHi6B-myT", "Uakgb_J5m9g-0JDMbcJqL", "N4f90aR2KqP7xLmV"],
    "nearbyGPSCoordinate": ["40.7128,-74.0060", "48.8566,2.3522", "35.6762,139.6503"],
    "networkInterface": ["eth0", "wlan0", "en0"],
    "noun": ["river", "system", "garden"],
    "number": ["555-123-4567", "+1-202-555-0174", "49-015-399-5832"],
    "numeric": ["12345", "9042", "007"],
    "octal": ["0o755", "0o644", "0o123"],
    "ordinalDirection": ["Northeast", "Southwest", "Northwest"],
    "paragraph": ["The quick brown fox jumps over the lazy dog.", "A small river flowed beside the old road.", "Bright clouds gathered above the city."],
    "paragraphs": ["First paragraph. Second paragraph.", "A short paragraph. Another short paragraph.", "One block of text. Another block of text."],
    "password": ["xK#9mP@q2r", "zT!7vL$w4n", "P@ssw0rd!42"],
    "past": ["2020-05-18T12:00:00.000Z", "2022-11-09T08:45:12.000Z", "2019-01-01T00:00:00.000Z"],
    "personPortrait": ["https://images.example.com/portrait-1.jpg", "https://images.example.com/portrait-2.jpg", "https://images.example.com/portrait-3.jpg"],
    "petName": ["Milo", "Luna", "Charlie"],
    "pin": ["1234", "0420", "9981"],
    "port": ["8080", "443", "3000"],
    "postalAddress": ["742 Evergreen Terrace, Springfield", "1600 Pennsylvania Ave NW, Washington", "221B Baker Street, London"],
    "preposition": ["above", "under", "beside"],
    "price": ["19.99", "4.50", "1299.00"],
    "product": ["Chair", "Keyboard", "Backpack"],
    "productAdjective": ["Handcrafted", "Sleek", "Practical"],
    "productDescription": ["Ergonomic chair with lumbar support.", "Wireless keyboard with quiet keys.", "Durable backpack for travel."],
    "productMaterial": ["Steel", "Cotton", "Wooden"],
    "productName": ["Handcrafted Steel Chair", "Sleek Cotton Shirt", "Practical Wooden Table"],
    "protocol": ["http", "https", "ftp"],
    "publisher": ["Penguin Books", "HarperCollins", "Vintage"],
    "rabbit": ["cottontail", "lop", "hare"],
    "recent": ["2026-06-22T15:04:00.000Z", "2026-06-20T09:12:31.000Z", "2026-06-18T21:44:10.000Z"],
    "recordLocator": ["A1B2C3", "ZX90QA", "MN7P4K"],
    "rgb": ["rgb(58, 123, 213)", "rgb(255, 107, 107)", "rgb(20, 184, 166)"],
    "rodent": ["capybara", "hamster", "squirrel"],
    "romanNumeral": ["IV", "XII", "MMXXVI"],
    "routingNumber": ["011000138", "021000021", "111000025"],
    "sample": ["brisk", "river", "lantern"],
    "seat": ["12A", "24C", "1F"],
    "secondaryAddress": ["Apt 4B", "Suite 200", "Unit 12"],
    "semver": ["3.4.1", "0.12.9", "2.0.0"],
    "sentence": ["The quick brown fox jumps over the lazy dog.", "A quiet morning settled over the town.", "Data moved cleanly through the system."],
    "sentences": ["The quick brown fox jumps. A quiet morning settled.", "Data moved cleanly. The service responded quickly.", "The sun rose. The city woke."],
    "series": ["The Broken Earth", "The Expanse", "Discworld"],
    "sex": ["female", "male", "intersex"],
    "sexType": ["female", "male", "intersex"],
    "slug": ["my-blog-post", "product-name-2026", "how-to-guide"],
    "snake": ["cobra", "python", "viper"],
    "songName": ["Blue in Green", "River", "Paranoid Android"],
    "soon": ["2026-06-24T10:00:00.000Z", "2026-06-25T09:30:00.000Z", "2026-06-27T14:15:00.000Z"],
    "space": ["sRGB", "display-p3", "rec2020"],
    "spice": ["cumin", "paprika", "cardamom"],
    "state": ["Colorado", "California", "New York"],
    "street": ["Maple Avenue", "Oak Street", "River Road"],
    "streetAddress": ["742 Evergreen Terrace", "1600 Pennsylvania Ave NW", "221B Baker Street"],
    "suffix": ["Jr.", "PhD", "III"],
    "symbol": ["@", "#", "%"],
    "text": ["Multiple sentences of generated text.", "A longer block of lorem-style content.", "Free-form placeholder text for a field."],
    "timeZone": ["America/New_York", "Europe/London", "Asia/Tokyo"],
    "title": ["The Silent Patient", "Kindred", "A Wizard of Earthsea"],
    "transactionDescription": ["payment transaction at Cafe Roma", "invoice payment for software", "withdrawal from ATM"],
    "transactionType": ["deposit", "withdrawal", "payment"],
    "type": ["sedan", "uuid", "carnivore"],
    "ulid": ["01HZXK9P8M6Z7C2R4QYF0V8N3", "01J0A1B2C3D4E5F6G7H8J9K0", "01H7Z6Y5X4W3V2U1T0S9R8Q7"],
    "unit": ["meter", "kelvin", "mole"],
    "upc": ["012345678905", "036000291452", "725272730706"],
    "url": ["https://example.com", "https://shop.io/products", "https://data.org/report"],
    "urlLoremFlickr": ["https://loremflickr.com/640/480", "https://loremflickr.com/320/240/city", "https://loremflickr.com/800/600/food"],
    "urlPicsumPhotos": ["https://picsum.photos/640/480", "https://picsum.photos/320/240", "https://picsum.photos/800/600"],
    "userAgent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64)", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)", "Mozilla/5.0 (X11; Linux x86_64)"],
    "username": ["jane_doe", "alex99", "mchen4"],
    "vehicle": ["Toyota Camry", "Ford F-150", "Tesla Model S"],
    "vegetable": ["carrot", "broccoli", "eggplant"],
    "verb": ["calculate", "navigate", "streamline"],
    "version": ["3.4.1", "0.12.9", "2.0.0"],
    "vin": ["1HGCM82633A004352", "JH4KA8260MC000000", "WBA3A5C50DF000000"],
    "vrm": ["AB12 CDE", "XY09 ZZZ", "LM56 NOP"],
    "weekday": ["Monday", "Wednesday", "Friday"],
    "word": ["algorithm", "systemic", "projection"],
    "words": ["fast red truck", "open source code", "quiet city street"],
    "zipCode": ["90210", "10001", "SW1A 1AA"],
    "zodiacSign": ["Aries", "Libra", "Capricorn"],
}


def _module_key(category: str) -> str:
    return category[0].lower() + category[1:]


def _label(method: str) -> str:
    chars = []
    for ch in method:
        if ch.isupper():
            chars.append(" ")
        chars.append(ch)
    return "".join(chars).strip().title()


def _description(category: str, method: str) -> str:
    label = _label(method).lower()
    category_name = category.lower()
    if method in {"type", "name", "description"}:
        return f"Random {category_name} {label}"
    return f"Random {label} for {category_name} data"


def _examples(category: str, method: str) -> list[str]:
    return METHOD_EXAMPLES.get(method, CATEGORY_EXAMPLES[category])


FAKERJS_FIELD_TYPES = {
    f"{_module_key(category)}.{method}": {
        "label": _label(method),
        "category": category,
        "description": _description(category, method),
        "examples": _examples(category, method),
        "path": f"{_module_key(category)}.{method}",
        "args": DEFAULT_ARGS.get(f"{_module_key(category)}.{method}", []),
        "fakerjs": True,
    }
    for category, methods in MODULE_METHODS.items()
    for method in methods
}


def get_fakerjs_field_types_grouped():
    grouped = {}
    for type_key, meta in FAKERJS_FIELD_TYPES.items():
        category = meta["category"]
        grouped.setdefault(category, []).append({
            "type": type_key,
            "label": meta["label"],
            "description": meta["description"],
            "examples": meta.get("examples", []),
            "advanced": meta.get("advanced", False),
        })
    return grouped
